# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"
  # VM Debian Server
  config.vm.define "debian_python"  do |debian_python|

    # VARIABLE HOSTNAME
    APP_NAME= "debian-python"

    # HOSTNAME
    debian_python.vm.hostname = APP_NAME

    # NETWORK
    debian_python.vm.network "public_network" ,ip: "192.168.0.134",mode: "bridge" ,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # MOUNTS
    debian_python.vm.synced_folder ".", "/vagrant", disabled: true
    debian_python.vm.synced_folder "./security", "/home/vagrant/security"
    debian_python.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_python.vm.synced_folder "../../scripts/", "/home/vagrant/scripts"

    # PROVIDER CUSTOMIZATIONS
    debian_python.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 4096
      vb.cpus = 3
    end

    # PROVISION
    debian_python.vm.provision "shell", path: "scripts/install.sh"

  end
end